id: AB41E42BA
base_file: f7EC8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:44:47.091588
  last_modified_at: 2022-06-17 11:44:47.091591
