id: AB41E42BA
base_file: f2A8B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:44:47.082443
  last_modified_at: 2022-06-17 11:44:47.082447
