id: AB41E42BA
base_file: f326A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:44:47.083799
  last_modified_at: 2022-06-17 11:44:47.083818
