id: AB41E42BA
base_file: fB24B.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:44:47.097169
  last_modified_at: 2022-06-17 11:44:47.097171
