id: AB41E42BA
base_file: f0BD6.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:44:47.080312
  last_modified_at: 2022-06-17 11:44:47.080319
